### ISSUE TITLE
MDFRobotoFontLoader+MDCTypographyAdditions.h assumes CocoaPods

### ISSUE THREAD

**Issue by Arcank** [material-foundation/material-roboto-font-loader-ios#6]
MDFRobotoFontLoader+MDCTypographyAdditions.h assumes CocoaPods

https://github.com/material-foundation/material-roboto-font-loader-ios/blob/stable/src/MDCTypographyAdditions/MDFRobotoFontLoader%2BMDCTypographyAdditions.h#L19
This is an issue when not using CocoaPods, as `MaterialTypography.h` is usually in `.../components/Typography/MaterialTypography.h`.

**Comment by Arcank** [comment]
Hmm, maybe I see what's going on.

1. I uploaded a PR on stable to fix (#7).
2. I realized I did a PR on stable instead of develop, so I uploaded a PR on develop (#8) and deleted the PR on stable (#7).
3. You merged #8 (to develop), then merged stable to develop (cb0a347c8860bef7ee33d888de3e7e933eecc554), then released 1.1.2.

Step 3 undid #8 on develop and in the release though :)

**Comment by randallli** [comment]
fixed by https://github.com/material-foundation/material-roboto-font-loader-ios/pull/8

**Comment by randallli** [comment]
Looks like if I add args to
pod lib lint --use-libraries
it passes.
